### ISSUE TITLE
English version: 'Overview' page is untranslated

### ISSUE THREAD

**Issue by alexfmpe** [gonimo/gonimo-website#14]
https://github.com/gonimo/gonimo-website/blob/b1af3b3c55fb4d6a4cc742929b36e9fdbe6f109c/lang/en.php#L434

**Comment by eskimor** [comment]
uh, thanks a lot! :-)

**Comment by eskimor** [comment]
That somehow slipped through ..

**Comment by eskimor** [comment]
Fixed by disabling the page. (It was actually never meant to be released that way)
