### ISSUE TITLE
Rephrase FAQ question

### ISSUE THREAD

**Issue by Kaligule** [gonimo/gonimo-website#15]
[Here](https://github.com/gonimo/gonimo-website/blob/9dce542895cbf35624ff48c08cb3a53cb05f95cb/lang/de.php#L240) we read the FAQ question:

> "Wer kann aller in meiner Familie sein?"

This is not a correct german sentence. I guess it was meant to be "Wer kann alle__s__ in meiner Familie sein?", but then the answer doesn't really fit the question in my opinion.

**Comment by eskimor** [comment]
First of all sorry for the late reply - I am getting way too many github notifications.

To the issue: I am not a linguist, but it does sound correct to me. (Maybe a difference between German German and Austrian German?) ...

I agree, that the answer does not exactly match the question. It should rather be something like "Wie wird geregelt wer einer Familie angehört?" Oder ähnlich.

**Comment by eskimor** [comment]
I'll change the question accordingly.

**Comment by eskimor** [comment]
Fixed on latest HEAD.

**Comment by Kaligule** [comment]
Nice, thanks. At least to _my_ german ears this sound much better.
